[2019-03-25 20:59:03,852]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-03-25 21:00:08,847]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-03-25 21:10:38,823]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-03-25 21:11:32,169]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-15 17:10:53,023]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-17 22:37:03,717]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-17 22:45:49,275]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-17 23:05:38,894]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-17 23:08:27,499]-[WARNING]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-17 23:25:18,414]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
